site_name: Documentation DS2
theme:
  name: material
  palette:
    primary: teal
  features:
    - navigation.expand
    - content.code.copy
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
